from django.db import models

# Create your models here.

# This table stores the player data which will not likely to change through years, based on 2022's data
class PlayerBasics(models.Model):
    id = models.IntegerField(default=0, primary_key= True)
    name = models.CharField(max_length=100, default='N/A')
    age = models.IntegerField(default=0)
    photo = models.CharField(max_length=400, default='N/A')
    nationality = models.CharField(max_length=100, default='N/A')
    flag = models.CharField(max_length=400, default='N/A')
    preferred_foot = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)

# These tables stores the player information which are not relevant for clustering
class PlayerInfo17(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A', null = True)

    def __str__(self):
        return str(self.id)


class PlayerInfo18(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)


class PlayerInfo19(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)


class PlayerInfo20(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)


class PlayerInfo21(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)


class PlayerInfo22(models.Model):
    id = models.ForeignKey(PlayerBasics, max_length=200, on_delete=models.CASCADE, primary_key= True)
    overall = models.FloatField(default=0.0)
    potential = models.FloatField(default=0.0)
    club = models.CharField(max_length=100, default='N/A')
    club_logo = models.CharField(max_length=400, default='N/A')
    value = models.CharField(max_length=20, default='N/A')
    wage = models.CharField(max_length=20, default='N/A')
    special = models.IntegerField(default=0)
    international_reputation = models.FloatField(default=0.0)
    work_rate = models.CharField(max_length=20, default='N/A')
    body_type = models.CharField(max_length=20, default='N/A')
    real_face = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default='N/A')
    jersey_number = models.IntegerField(default=0)
    joined = models.DateTimeField()
    loan_from = models.CharField(max_length=100, default='N/A')
    contract_valid_until = models.IntegerField(default=2022)
    height = models.CharField(max_length=10, default='N/A')
    weight = models.CharField(max_length=10, default='N/A')
    best_position = models.CharField(max_length=10, default='N/A')
    best_overall = models.FloatField(default=0.0)
    release_clause = models.CharField(max_length=10, default='N/A')

    def __str__(self):
        return str(self.id)

# These tables stores the player data which will be used in algorithms
class PlayerStatus17(models.Model):
    id = models.ForeignKey(PlayerInfo17, on_delete=models.CASCADE, primary_key= True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)


class PlayerStatus18(models.Model):
    id = models.ForeignKey(PlayerInfo18, on_delete=models.CASCADE, primary_key= True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)


class PlayerStatus19(models.Model):
    id = models.ForeignKey(PlayerInfo19, on_delete=models.CASCADE, primary_key= True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)


class PlayerStatus20(models.Model):
    id = models.ForeignKey(PlayerInfo20, on_delete=models.CASCADE, primary_key= True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)


class PlayerStatus21(models.Model):
    id = models.ForeignKey(PlayerInfo21, on_delete=models.CASCADE, primary_key= True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)


class PlayerStatus22(models.Model):
    id = models.ForeignKey(PlayerInfo22, on_delete=models.CASCADE, primary_key=True)
    week_foot = models.FloatField(default=0.0)
    skill_moves = models.FloatField(default=0.0)
    crossing = models.FloatField(default=0.0)
    finishing = models.FloatField(default=0.0)
    heading_accuracy = models.FloatField(default=0.0)
    short_passing = models.FloatField(default=0.0)
    volleys = models.FloatField(default=0.0)
    dribbling = models.FloatField(default=0.0)
    curve = models.FloatField(default=0.0)
    fk_accuracy = models.FloatField(default=0.0)
    long_passing = models.FloatField(default=0.0)
    ball_control = models.FloatField(default=0.0)
    acceleration = models.FloatField(default=0.0)
    sprint_speed = models.FloatField(default=0.0)
    agility = models.FloatField(default=0.0)
    reactions = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)
    shot_power = models.FloatField(default=0.0)
    jumping = models.FloatField(default=0.0)
    stamina = models.FloatField(default=0.0)
    strength = models.FloatField(default=0.0)
    long_shots = models.FloatField(default=0.0)
    aggression = models.FloatField(default=0.0)
    interceptions = models.FloatField(default=0.0)
    positioning = models.FloatField(default=0.0)
    vision = models.FloatField(default=0.0)
    penalties = models.FloatField(default=0.0)
    composure = models.FloatField(default=0.0)
    marking = models.FloatField(default=0.0)
    standing_tackle = models.FloatField(default=0.0)
    sliding_tackle = models.FloatField(default=0.0)
    gk_diving = models.FloatField(default=0.0)
    gk_handling = models.FloatField(default=0.0)
    gk_kicking = models.FloatField(default=0.0)
    gk_positioning = models.FloatField(default=0.0)
    gk_reflexes = models.FloatField(default=0.0)
    defensive_awareness = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.id)

